name: vibes
description: "New vibes."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  icons_plus: ^5.0.0
  lottie: ^3.1.0
  path_provider: ^2.1.2
  toastification: ^1.2.1
  animated_toggle_switch: ^0.8.2
  date_format: ^2.0.7
  emoji_selector: ^0.0.6
  uuid: ^4.3.3
  highlight_text: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
